"""
sandbox.py
~~~~~~~~~~~~

This module defines a small execution *sandbox* for running Python code in
isolation.  It is used to execute implementations generated by the LLM,
preventing the code from affecting the application's global environment.
Uses the ``multiprocessing`` module to create a separate process with a time
limit.  If the function exceeds the allocated time or raises an exception,
it is caught and returned in a controlled manner.

The sandbox is not completely safe for executing arbitrary code in production
(for example, it could use too much memory or access sensitive resources).
For a production environment it would be necessary to isolate execution in
containers or use specialized services like AWS Lambda, Cloud Run or operating
system sandboxing technologies.
"""

from __future__ import annotations

import multiprocessing as mp
import sys
import traceback
from types import SimpleNamespace
from typing import Any, Callable, Dict, Tuple


def _worker_func(code: str, func_name: str, args: Tuple, kwargs: Dict, result_queue: mp.Queue) -> None:
    """Internal function executed in a separate process.

    Dynamically loads the code, obtains the function ``func_name`` and executes
    it with the provided arguments.  The result (or exception) is placed in
    ``result_queue``.
    """
    try:
        # Build a temporary module in an execution dict
        exec_globals: Dict[str, Any] = {}
        exec(code, exec_globals)
        func = exec_globals.get(func_name)
        if not callable(func):
            raise AttributeError(f"Function {func_name} not found in the provided code")
        result = func(*args, **kwargs)
        result_queue.put((True, result))
    except Exception:
        exc_type, exc_value, tb = sys.exc_info()
        tb_str = "".join(traceback.format_exception(exc_type, exc_value, tb))
        result_queue.put((False, tb_str))


def run_in_sandbox(code: str, func_name: str, args: Tuple = (), kwargs: Dict[str, Any] = None, timeout: float = 2.0) -> Tuple[bool, Any]:
    """Executes a function defined in source code within an isolated process.

    :param code: String with Python code (must define ``func_name``).
    :param func_name: Name of the function to execute.
    :param args: Tuple of positional arguments to pass to the function.
    :param kwargs: Dictionary of named arguments to pass to the function.
    :param timeout: Maximum execution time in seconds.
    :return: Tuple ``(success, result)``.  If ``success`` is ``True``,
      ``result`` contains the value returned by the function; otherwise,
      it contains the exception traceback.
    """
    kwargs = kwargs or {}
    result_queue: mp.Queue = mp.Queue()
    process = mp.Process(target=_worker_func, args=(code, func_name, args, kwargs, result_queue))
    process.start()
    process.join(timeout)
    if process.is_alive():
        process.terminate()
        return False, f"Execution time exceeded after {timeout} seconds"
    if not result_queue.empty():
        return result_queue.get()
    return False, "Could not get result from child process"